---
name: Publish
on:
  # the 1st condition
  workflow_run:
    workflows: ["Mega-Linter", "Unit-Test"]
    branches: [main]
    types:
      - completed
jobs:
  deploy-packages:
    # the 2nd condition
    if: github.event.workflow_run.conclusion == 'success'
    name: PushToDockerhub
    runs-on: ubuntu-latest
    steps:
      - name: push to dockerhub
        run: echo foo
    